# Generated by Django 3.1.3 on 2022-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(max_length=20)),
                ('priority', models.CharField(default=None, max_length=10)),
                ('customer', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=200)),
                ('status', models.CharField(default='New', max_length=50)),
                ('assigned_to', models.CharField(default='', max_length=50)),
                ('current_queue', models.CharField(default='PL.Bridge.BE.Events', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
