# Generated by Django 3.1.3 on 2022-04-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('incident_number', models.CharField(max_length=20)),
                ('priority', models.CharField(default=None, max_length=10)),
                ('customer', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TicketUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('ticket_id', models.IntegerField()),
            ],
        ),
    ]
