# Generated by Django 3.1.3 on 2022-07-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepage', '0002_user_is_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='assets/img/illustrations/profiles/profile-1.png', max_length=255),
        ),
    ]
