# Generated by Django 3.1.3 on 2022-07-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepage', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FilePathField(default='/static/assets/img/illustrations/profiles/profile-1.png', max_length=255),
        ),
    ]
