# Generated by Django 3.1.3 on 2022-07-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepage', '0004_auto_20220705_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FilePathField(default='/assets/img/illustrations/profiles/profile-1.png', max_length=255),
        ),
    ]
