# Generated by Django 3.1.3 on 2022-07-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepage', '0007_auto_20220705_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FilePathField(path='static/assets/img/illustrations/profiles/profile-1.png'),
        ),
    ]
