# Generated by Django 3.1.3 on 2022-07-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepage', '0009_auto_20220705_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FilePathField(path='/app/static/assets/img/profiles/profile-1.png'),
        ),
    ]
