# Generated by Django 3.1.3 on 2022-07-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepage', '0011_auto_20220705_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='/app/static/assets/img/profiles/profile-1.png', max_length=255),
        ),
    ]
