# Generated by Django 3.1.3 on 2022-07-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepage', '0012_auto_20220705_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
